

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star1', '1', '철수', '010334', 'starqzqz1@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star2', '1', '영희', '010334', 'starqzqz2@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star3', '1', '소나무', '010334', 'starqzqz3@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star4', '1', '산', '010334', 'starqzqz4@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star5', '1', '바다', '010334', 'starqzqz5@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUE7
    (MEMBER_SEQ.NEXTVAL, 'star6', '1', '철수', '010334', 'starqzqz6@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star8', '1', '물', '010334', 'starqzqz7@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star9', '1', '기린', '010334', 'starqzqz8@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star10', '1', '호랑이', '010334', 'starqzqz9@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star11', '1', '하마', '010334', 'starqzqz10@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star12', '1', '강', '010334', 'starqzqz11@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star13', '1', '바람', '010334', 'starqzqz12@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star14', '1', '책', '010334', 'starqzqz13@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star15', '1', '남희', '010334', 'starqzqz14@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star16', '1', '들', '010334', 'starqzqz15@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star17', '1', '논', '010334', 'starqzqz16@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star18', '1', '구름', '010334', 'starqzqz17@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star19', '1', '원숭이', '010334', 'starqzqz18@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star20', '1', '강아지', '010334', 'starqzqz19@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star21', '1', '고양이', '010334', 'starqzqz20@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star22', '1', '도마뱀', '010334', 'starqzqz21@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star23', '1', '들개', '010334', 'starqzqz22@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star24', '1', '휴대폰', '010334', 'starqzqz23@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star25', '1', '폰', '010334', 'starqzqz24@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star26', '1', '공격', '010334', 'starqzqz25@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star27', '1', '수비', '010334', 'starqzqz26@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star28', '1', '반격', '010334', 'starqzqz27@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star29', '1', '군인', '010334', 'starqzqz28@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star30', '1', '전쟁', '010334', 'starqzqz29@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star31', '1', '습격', '010334', 'starqzqz30@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star32', '1', '전략', '010334', 'starqzqz31@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'sta33', '1', '전술', '010334', 'starqzqz32@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star34', '1', '축구', '010334', 'starqzqz33@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star35', '1', '선수', '010334', 'starqzqz34@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star36', '1', '야구', '010334', 'starqzqz35@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star37', '1', '농구', '010334', 'starqzqz36@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star38', '1', '배구', '010334', 'starqzqz37@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star39', '1', '양궁', '010334', 'starqzqz38@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star40', '1', '태권도', '010334', 'starqzqz39@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star41', '1', '절권도', '010334', 'starqzqz40@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;V

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star42', '1', '검도', '010334', 'starqzqz41@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star43', '1', '합기도', '010334', 'starqzqz42@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star44', '1', '무술', '010334', 'starqzqz43@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star45', '1', '성공', '010334', 'starqzqz44@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star46', '1', '실패', '010334', 'starqzqz45@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star47', '1', '실수', '010334', 'starqzqz46@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star48', '1', '수락', '010334', 'starqzqz47@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star49', '1', '거절', '010334', 'starqzqz48@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star50', '1', '협상', '010334', 'starqzqz49@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;

INSERT INTO MEMBER
    (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_POSTCODE, MEMBER_ROAD_ADDRESS, MEMBER_DETAIL_ADDRESS, MEMBER_AGREE_STATE, MEMBER_SIGN_UP, MEMBER_PW_MODIFIED, MEMBER_INFO_MODIFIED, MEMBER_SESSION_ID, MEMBER_SESSION_LIMIT)
VALUES
    (MEMBER_SEQ.NEXTVAL, 'star1', '1', '협약', '010334', 'starqzqz50@naver.com', '21', '서울시서울시서울시서울시', '000길1011호', 1, SYSDATE, SYSDATE, SYSDATE, '1', SYSDATE);
COMMIT;